[CmdletBinding()]
param(
    [ValidateSet("local", "server")]
    [string]$Mode = "local",

    [string]$Dir = "",
    [int]$Port = 8317,
    [string]$Domain = "",
    [string]$ApiKey = "",
    [string]$ManagementPassword = "",
    [string]$Image = "eceasy/cli-proxy-api:latest",
    [string]$Timezone = "Asia/Shanghai",
    [switch]$OAuthPorts,
    [switch]$NoStart,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

function Show-Help {
    @'
CPA Auto one-click installer for Windows PowerShell

Usage:
  powershell -ExecutionPolicy Bypass -File .\install.ps1
  powershell -ExecutionPolicy Bypass -File .\install.ps1 -Mode local -Port 8317
  powershell -ExecutionPolicy Bypass -File .\install.ps1 -Mode server -Domain cpa.example.com

Options:
  -Mode local|server       local binds to 127.0.0.1, server opens to the network.
  -Dir PATH                Install directory. Default: %USERPROFILE%\cpa-local.
  -Port PORT               Host port for CLIProxyAPI. Default: 8317.
  -Domain DOMAIN           Enable Caddy HTTPS reverse proxy for this domain.
  -ApiKey KEY              Client API key. Default: auto-generated.
  -ManagementPassword P    Management key for /management.html. Default: auto-generated.
  -Image IMAGE             Docker image. Default: eceasy/cli-proxy-api:latest.
  -Timezone TZ             Timezone. Default: Asia/Shanghai.
  -OAuthPorts              Expose OAuth helper callback ports on 0.0.0.0.
  -NoStart                 Write files but do not start containers.
  -Help                    Show this help.

Docker Desktop must be installed and running before using this script.
'@
}

if ($Help) {
    Show-Help
    exit 0
}

if (-not [string]::IsNullOrWhiteSpace($Domain)) {
    $Mode = "server"
}

if ([string]::IsNullOrWhiteSpace($Dir)) {
    if ($Mode -eq "server") {
        $Dir = Join-Path $env:USERPROFILE "cpa-server"
    }
    else {
        $Dir = Join-Path $env:USERPROFILE "cpa-local"
    }
}

$UseCaddy = -not [string]::IsNullOrWhiteSpace($Domain)
if ($Mode -eq "local" -or $UseCaddy) {
    $BindHost = "127.0.0.1"
}
else {
    $BindHost = "0.0.0.0"
}

if ($OAuthPorts) {
    $OAuthBindHost = "0.0.0.0"
}
else {
    $OAuthBindHost = "127.0.0.1"
}

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function New-HexSecret([int]$Bytes) {
    $buffer = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($buffer)
    }
    finally {
        $rng.Dispose()
    }
    return (($buffer | ForEach-Object { $_.ToString("x2") }) -join "")
}

function Get-DotEnvValue([string]$Path, [string]$Key) {
    if (-not (Test-Path $Path)) {
        return ""
    }
    $escaped = [regex]::Escape($Key)
    foreach ($line in Get-Content -Path $Path) {
        if ($line -match "^$escaped=(.*)$") {
            return $Matches[1]
        }
    }
    return ""
}

function Set-DotEnvValue([string]$Path, [string]$Key, [string]$Value) {
    $lines = @()
    if (Test-Path $Path) {
        $lines = @(Get-Content -Path $Path)
    }

    $escaped = [regex]::Escape($Key)
    $found = $false
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^$escaped=") {
            $lines[$i] = "$Key=$Value"
            $found = $true
        }
    }

    if (-not $found) {
        $lines += "$Key=$Value"
    }

    Set-Content -Path $Path -Value $lines -Encoding ascii
}

function Test-DockerReady {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker was not found. On Windows/macOS, install and start Docker Desktop first: https://www.docker.com/products/docker-desktop/ . Then rerun this script."
    }

    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker is installed but not running. Start Docker Desktop and wait until it says Docker is running, then rerun this script."
    }

    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose v2 was not found. Update Docker Desktop, then rerun this script."
    }
}

function Invoke-Compose([string[]]$ComposeArgs) {
    $args = @("compose", "-f", "docker-compose.yml")
    if ($script:UseCaddy) {
        $args += @("-f", "docker-compose.caddy.yml")
    }
    $args += $ComposeArgs
    & docker @args
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed: $($ComposeArgs -join ' ')"
    }
}

function Write-ConfigFile {
    $config = @"
# Generated by CPA Auto.
# Edit this file and run .\cpactl.ps1 restart to apply changes.

host: ""
port: 8317

tls:
  enable: false
  cert: ""
  key: ""

remote-management:
  allow-remote: true
  secret-key: "$ManagementPassword"
  disable-control-panel: false
  panel-github-repository: "https://github.com/router-for-me/Cli-Proxy-API-Management-Center"

auth-dir: "~/.cli-proxy-api"

api-keys:
  - "$ApiKey"

debug: false

pprof:
  enable: false
  addr: "127.0.0.1:8316"

commercial-mode: false
logging-to-file: true
logs-max-total-size-mb: 512
error-logs-max-files: 10
usage-statistics-enabled: false
redis-usage-queue-retention-seconds: 300

proxy-url: ""
force-model-prefix: false
passthrough-headers: false

request-retry: 3
max-retry-credentials: 0
max-retry-interval: 30
disable-cooling: false
disable-image-generation: false

quota-exceeded:
  switch-project: true
  switch-preview-model: true
  antigravity-credits: true

routing:
  strategy: "round-robin"
  session-affinity: false
  session-affinity-ttl: "1h"

codex:
  identity-confuse: false

ws-auth: true
enable-gemini-cli-endpoint: false
nonstream-keepalive-interval: 0
"@
    Set-Content -Path "config.yaml" -Value $config -Encoding ascii
}

function Write-ComposeFile {
    $compose = @'
services:
  cli-proxy-api:
    image: "${CPA_IMAGE:-eceasy/cli-proxy-api:latest}"
    container_name: cli-proxy-api
    pull_policy: always
    restart: unless-stopped
    environment:
      TZ: "${TZ:-Asia/Shanghai}"
      MANAGEMENT_PASSWORD: "${MANAGEMENT_PASSWORD:?MANAGEMENT_PASSWORD is required}"
      DEPLOY: "${DEPLOY:-}"
    ports:
      - "${BIND_HOST:-127.0.0.1}:${SERVER_PORT:-8317}:8317"
      - "${OAUTH_BIND_HOST:-127.0.0.1}:8085:8085"
      - "${OAUTH_BIND_HOST:-127.0.0.1}:1455:1455"
      - "${OAUTH_BIND_HOST:-127.0.0.1}:54545:54545"
      - "${OAUTH_BIND_HOST:-127.0.0.1}:51121:51121"
      - "${OAUTH_BIND_HOST:-127.0.0.1}:11451:11451"
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    healthcheck:
      test: ["CMD-SHELL", "wget -q -T 5 -O - http://127.0.0.1:8317/healthz >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
'@
    Set-Content -Path "docker-compose.yml" -Value $compose -Encoding ascii
}

function Write-CaddyFiles {
    if (-not $script:UseCaddy) {
        return
    }

    $caddyCompose = @'
services:
  caddy:
    image: caddy:2-alpine
    container_name: cli-proxy-api-caddy
    restart: unless-stopped
    depends_on:
      - cli-proxy-api
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - default
'@
    Set-Content -Path "docker-compose.caddy.yml" -Value $caddyCompose -Encoding ascii

    $caddyfile = @"
$Domain {
    encode gzip zstd
    reverse_proxy cli-proxy-api:8317
}
"@
    Set-Content -Path "Caddyfile" -Value $caddyfile -Encoding ascii
}

function Write-HelperScript {
    $helper = @'
param(
    [string]$Command = "help",
    [string]$Service = "cli-proxy-api"
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Get-DotEnvValue([string]$Path, [string]$Key) {
    if (-not (Test-Path $Path)) {
        return ""
    }
    $escaped = [regex]::Escape($Key)
    foreach ($line in Get-Content -Path $Path) {
        if ($line -match "^$escaped=(.*)$") {
            return $Matches[1]
        }
    }
    return ""
}

$Domain = Get-DotEnvValue ".env" "DOMAIN"
$Mode = Get-DotEnvValue ".env" "MODE"
$Port = Get-DotEnvValue ".env" "SERVER_PORT"
$UseCaddy = -not [string]::IsNullOrWhiteSpace($Domain) -and (Test-Path "docker-compose.caddy.yml")

function Invoke-Compose([string[]]$ComposeArgs) {
    $args = @("compose", "-f", "docker-compose.yml")
    if ($script:UseCaddy) {
        $args += @("-f", "docker-compose.caddy.yml")
    }
    $args += $ComposeArgs
    & docker @args
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed: $($ComposeArgs -join ' ')"
    }
}

function Show-Help {
    @"
Usage: .\cpactl.ps1 COMMAND

Commands:
  start       Start CPA
  stop        Stop CPA
  restart     Restart CPA
  status      Show container status
  logs        Follow CPA logs
  update      Pull latest image and restart
  health      Check /healthz
  url         Print access URL
  password    Print saved credentials
  backup      Create a zip backup in the current directory
  help        Show this help
"@
}

switch ($Command.ToLowerInvariant()) {
    "start" {
        Invoke-Compose @("up", "-d")
    }
    "stop" {
        Invoke-Compose @("down")
    }
    "restart" {
        Invoke-Compose @("restart")
    }
    "status" {
        Invoke-Compose @("ps")
    }
    "logs" {
        Invoke-Compose @("logs", "-f", $Service)
    }
    "update" {
        Invoke-Compose @("pull")
        Invoke-Compose @("up", "-d")
    }
    "health" {
        if ([string]::IsNullOrWhiteSpace($Port)) { $Port = "8317" }
        Invoke-RestMethod -Uri "http://127.0.0.1:$Port/healthz"
    }
    "url" {
        if (-not [string]::IsNullOrWhiteSpace($Domain)) {
            Write-Host "https://$Domain"
        }
        elseif ($Mode -eq "local") {
            Write-Host "http://localhost:$Port"
        }
        else {
            Write-Host "http://SERVER_IP:$Port"
        }
    }
    "password" {
        if (Test-Path ".credentials") {
            Get-Content ".credentials"
        }
        else {
            Write-Host "Open .env and check API_KEY / MANAGEMENT_PASSWORD."
        }
    }
    "backup" {
        $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
        $backup = "cpa-backup-$stamp.zip"
        $paths = @(".env", ".credentials", "config.yaml", "docker-compose.yml", "docker-compose.caddy.yml", "Caddyfile", "auths", "logs", "caddy_data", "caddy_config") | Where-Object { Test-Path $_ }
        Compress-Archive -Path $paths -DestinationPath $backup -Force
        Write-Host "Backup created: $backup"
    }
    "help" {
        Show-Help
    }
    default {
        Write-Host "Unknown command: $Command"
        Show-Help
        exit 1
    }
}
'@
    Set-Content -Path "cpactl.ps1" -Value $helper -Encoding ascii
}

function Wait-ForHealth {
    if ($NoStart) {
        return
    }
    for ($i = 0; $i -lt 30; $i++) {
        try {
            Invoke-RestMethod -Uri "http://127.0.0.1:$Port/healthz" -TimeoutSec 3 | Out-Null
            return
        }
        catch {
            Start-Sleep -Seconds 2
        }
    }
    Write-Host "CPA did not answer http://127.0.0.1:$Port/healthz yet. Check .\cpactl.ps1 logs." -ForegroundColor Yellow
}

if (-not $NoStart) {
    Test-DockerReady
}

Write-Step "Preparing CPA Auto in $Dir"
New-Item -ItemType Directory -Force -Path $Dir | Out-Null
Set-Location $Dir
New-Item -ItemType Directory -Force -Path "auths", "logs" | Out-Null
if ($UseCaddy) {
    New-Item -ItemType Directory -Force -Path "caddy_data", "caddy_config" | Out-Null
}

if (Test-Path ".env") {
    $backup = ".env.backup.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item ".env" $backup
    Write-Step "Existing .env found, backup saved as $backup"
}
else {
    Set-Content -Path ".env" -Value @("# Generated by CPA Auto.", "# You can edit this file and rerun .\cpactl.ps1 restart.") -Encoding ascii
}

$ExistingApiKey = Get-DotEnvValue ".env" "API_KEY"
$ExistingManagementPassword = Get-DotEnvValue ".env" "MANAGEMENT_PASSWORD"

if ([string]::IsNullOrWhiteSpace($ApiKey)) { $ApiKey = $ExistingApiKey }
if ([string]::IsNullOrWhiteSpace($ApiKey)) { $ApiKey = "cpa-$(New-HexSecret 24)" }
if ([string]::IsNullOrWhiteSpace($ManagementPassword)) { $ManagementPassword = $ExistingManagementPassword }
if ([string]::IsNullOrWhiteSpace($ManagementPassword)) { $ManagementPassword = "cpa-mgmt-$(New-HexSecret 18)" }

Set-DotEnvValue ".env" "MODE" $Mode
Set-DotEnvValue ".env" "CPA_IMAGE" $Image
Set-DotEnvValue ".env" "BIND_HOST" $BindHost
Set-DotEnvValue ".env" "OAUTH_BIND_HOST" $OAuthBindHost
Set-DotEnvValue ".env" "SERVER_PORT" "$Port"
Set-DotEnvValue ".env" "DOMAIN" $Domain
Set-DotEnvValue ".env" "TZ" $Timezone
Set-DotEnvValue ".env" "API_KEY" $ApiKey
Set-DotEnvValue ".env" "MANAGEMENT_PASSWORD" $ManagementPassword
Set-DotEnvValue ".env" "HTTP_PORT" "80"
Set-DotEnvValue ".env" "HTTPS_PORT" "443"

Write-ConfigFile
Write-ComposeFile
Write-CaddyFiles
Write-HelperScript

if ($UseCaddy) {
    $AccessUrl = "https://$Domain"
}
elseif ($Mode -eq "local") {
    $AccessUrl = "http://localhost:$Port"
}
else {
    $AccessUrl = "http://SERVER_IP:$Port"
}

$credentials = @(
    "CPA_URL=$AccessUrl",
    "MANAGEMENT_URL=$AccessUrl/management.html",
    "API_KEY=$ApiKey",
    "MANAGEMENT_PASSWORD=$ManagementPassword",
    "INSTALL_DIR=$Dir"
)
Set-Content -Path ".credentials" -Value $credentials -Encoding ascii

if (-not $NoStart) {
    Write-Step "Pulling Docker images"
    Invoke-Compose @("pull")
    Write-Step "Starting CPA"
    Invoke-Compose @("up", "-d")
    Write-Step "Waiting for health check"
    Wait-ForHealth
    Write-Step "Container status"
    Invoke-Compose @("ps")
}
else {
    Write-Host "Files written, containers not started because -NoStart was used." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "CPA is ready." -ForegroundColor Green
Write-Host ""
Write-Host "URL:                 $AccessUrl"
Write-Host "Management panel:    $AccessUrl/management.html"
Write-Host "Management password: $ManagementPassword"
Write-Host "API key:             $ApiKey"
Write-Host "Install dir:         $Dir"
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  cd `"$Dir`""
Write-Host "  powershell -ExecutionPolicy Bypass -File .\cpactl.ps1 status"
Write-Host "  powershell -ExecutionPolicy Bypass -File .\cpactl.ps1 logs"
Write-Host "  powershell -ExecutionPolicy Bypass -File .\cpactl.ps1 update"
Write-Host "  powershell -ExecutionPolicy Bypass -File .\cpactl.ps1 password"
Write-Host ""
Write-Host "Credentials were saved to:"
Write-Host "  $Dir\.credentials"

if ($UseCaddy) {
    Write-Host ""
    Write-Host "Domain note: make sure $Domain points to this machine, and open TCP ports 80 and 443." -ForegroundColor Yellow
}

if (-not $OAuthPorts) {
    Write-Host ""
    Write-Host "OAuth note: helper callback ports are bound to 127.0.0.1 by default. Use -OAuthPorts if web-panel login needs direct callback access." -ForegroundColor Yellow
}
